// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnbtylngdapmaxithsrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuYnR5bG5nZGFwbWF4aXRoc3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NzM0MzAsImV4cCI6MjA1NTE0OTQzMH0.k3681hn-V_SlAIp-jYrxToxnFUK99STT6SwJ8lB4kBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);